apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
        - name: chess
          image: thomasahle/chess
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chess-service
spec:
  selector:
    app: chess
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
