apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: jasonnguyen/pacman
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-service
spec:
  selector:
    app: pacman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
