apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snakegame
  template:
    metadata:
      labels:
        app: snakegame
    spec:
      containers:
        - name: snakegame
          image: jakevdp/snake-game
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: snakegame-service
spec:
  selector:
    app: snakegame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
