apiVersion: apps/v1
kind: Deployment
metadata:
  name: tindog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tindog
  template:
    metadata:
      labels:
        app: tindog
    spec:
      containers:
        - name: tindog
          image: liberace1/tindog:latest
          ports:
            - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: tindog-service
spec:
  selector:
    app: tindog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
