apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappybird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flappybird
  template:
    metadata:
      labels:
        app: flappybird
    spec:
      containers:
        - name: flappybird
          image: liberace1/flappybird-web-game
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flappybird-service
spec:
  selector:
    app: flappybird
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
