apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-retro-web-game
  labels:
    app: multi-retro-web-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-retro-web-game
  template:
    metadata:
      labels:
        app: multi-retro-web-game
    spec:
      containers:
        - name: retro-game
          image: liberace1/multi-retro-web-game:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: multi-retro-web-game-service
spec:
  selector:
    app: multi-retro-web-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
